import 'package:dio/dio.dart';
import 'package:embone/core/cubit/global_cubit.dart';
import 'package:embone/core/database/api/dio_consumer.dart';
import 'package:embone/core/network/local_network.dart';
import 'package:embone/features/business_account/auth_bussniss_acc/data/repo/account_repo.dart';
import 'package:embone/features/business_account/auth_bussniss_acc/data/repo/category_repo.dart';
import 'package:embone/features/business_account/home/data/repo/account_repo.dart';
import 'package:embone/features/business_account/product/data/repo/product_repo.dart';
import 'package:embone/features/business_account/product/data/repo/service_repo.dart';
import 'package:embone/features/client/auth/data/repo/forget_password_repo.dart';
import 'package:embone/features/client/auth/data/repo/login_repo.dart';
import 'package:embone/features/client/auth/data/repo/register_repo.dart';
import 'package:embone/features/client/cart/data/repo/cart_repo.dart';
import 'package:embone/features/client/chat/data/repo/chat_repo.dart';
import 'package:embone/features/client/checkout/data/repo/checkout_repo.dart';
import 'package:embone/features/client/contacts/data/repo/friends_repo.dart';
import 'package:embone/features/client/home/data/repo/home_repo.dart';
import 'package:embone/features/client/locations/data/repo/locations_repo.dart';
import 'package:embone/features/client/menu/data/repo/account_repo.dart';
import 'package:embone/features/client/menu/data/repo/address_repo.dart';
import 'package:embone/features/client/menu/data/repo/business_repo.dart';
import 'package:embone/features/client/menu/data/repo/faq_repo.dart';
import 'package:embone/features/client/menu/data/repo/offer_repo.dart';
import 'package:embone/features/client/menu/data/repo/privacy_policy_repo.dart';
import 'package:embone/features/client/menu/data/repo/profile_repo.dart';
import 'package:embone/features/client/menu/data/repo/wallet_repo.dart';
import 'package:embone/features/client/menu/data/repo/wishlist_repo.dart';
import 'package:embone/features/client/notifications/data/repo/notifications_repo.dart';
import 'package:embone/features/client/order/data/repo/orders_repo.dart';
import 'package:embone/features/client/product_Details/data/repo/comment_repo.dart';
import 'package:embone/features/client/search/data/repo/search_repo.dart';
import 'package:embone/features/client/shop/data/repo/shop_repo.dart';
import 'package:get_it/get_it.dart';

final sl = GetIt.instance;
void initServiceLocator() {
//!external
  sl.registerLazySingleton(() => CacheHelper());
  sl.registerLazySingleton(() => GlobalCubit());
  sl.registerLazySingleton(() => Dio());
  sl.registerLazySingleton(() => DioConsumer(sl<Dio>()));
  sl.registerLazySingleton(() => LoginRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => RegisterRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => LocationRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ForgetPasswordRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => SearchRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ShopRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => HomeRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => NotificationsRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => WishlistRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ProfileRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => AccountRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => CommentRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => CartRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => AddressRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => CategoryRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => CheckoutRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => FriendsRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ChatRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => OrderRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => WalletRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ProductRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => ServiceRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => BusinessAccountRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => FaqRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => BusinessRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => OfferRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => AccountsRepo(sl<DioConsumer>()));
  sl.registerLazySingleton(() => PrivacyPolicyRepo(sl<DioConsumer>()));

  // sl.registerLazySingleton(() => DataConnectionChecker());
  // sl.registerLazySingleton(() => NetworkInfoImpl(sl<DataConnectionChecker>()));
  //! Repositorys
}
